# fly.toml app configuration file generated for contax-twilio-ws--no-deploy on 2025-09-26T14:48:46+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'contax-twilio-ws--no-deploy'
primary_region = 'yyz'

[build]

[http_service]
  internal_port = 8787
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

[checks]
  [checks.health]
    port = 8787
    type = 'http'
    interval = '10s'
    timeout = '2s'
    grace_period = '5s'
    path = '/health'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
